[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "flids"
version = "1.0.0"
description = "Privacy-Preserving FL-based Intrusion Detection Experiments"
license = "Apache-2.0"
dependencies = [ "flwr[simulation]>=1.24.0", "flwr-datasets[vision]>=0.5.0", "torch==2.8.0", "torchvision==0.23.0",]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "flids.server_app:app"
clientapp = "flids.client_app:app"

[tool.flwr.app.config]
experiment-name = "test"
num-clients = 10
run-inversion = true 
seed = 2
num-server-rounds = 10 
fraction-evaluate = 0.5
optimizer = "adam"
learning-rate = 0.001
weight-decay = 0
prox-mu = 0.001
local-epochs = 1 
local-batches = 1
batch-size = 1 
shuffle = false 
window-size = 20
epsilon = 10 
delta = 0.00001
clipping_norm = 2 
sensitivity = 0.5
attack-lr = 1.0
attack-rounds = 25
attack-max-iter = 5
attack-history-size = 10
attack-reg = 0
num-clients-to-attack = 2 

[tool.hatch.build.targets.wheel]
packages = [ ".",]
