[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "quickstart-pytorch"
version = "1.0.0"
description = "Federated Learning with PyTorch and Flower (Quickstart Example)"
license = "Apache-2.0"
dependencies = [ "flwr[simulation]>=1.24.0", "flwr-datasets[vision]>=0.5.0", "torch==2.8.0", "torchvision==0.23.0",]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "pytorchexample.server_app:app"
clientapp = "pytorchexample.client_app:app"

[tool.flwr.app.config]
experiment-name = "tune-noise"
run-inversion = false
seed = 2
num-server-rounds = 35
fraction-evaluate = 0.5
learning-rate = 0.001
weight-decay = 0.0001
prox-mu = 0
local-epochs = 3
local-batches = 1
batch-size = 32
shuffle = true
window-size = 30
epsilon = 10
delta = 1e-5
clipping_norm = 10
sensitivity = 1
attack-lr = 0.001
attack-rounds = 1000
attack-reg = 1e-5

[tool.hatch.build.targets.wheel]
packages = [ ".",]
